import { ThemeProvider } from "@/components/theme-provider";
import { Space_Grotesk } from "next/font/google";
import { Metadata } from "next";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gab",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.svg',
  },
 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <head>
    <link rel="icon" href="." sizes="any" />
  </head>
      <body className={spaceGrotesk.className}>  
      <link rel="icon" href="./Jake.svg" sizes="any" />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}